// This file is in AsciiDoc format. It is the source for README.html.
:Compact-Option:

bali-sdk
========

ULTRA IMPORTANT WARNING! THIS PROJECT COMES WITH NO RESPONSIBILITY OR WARRANTY OF ANY KIND!
YOU USE IT AT YOUR SOLE OWN RISK. IN PARTICULAR, YOU ARE THE ONLY RESPONSIBLE IF YOU BRICK YOUR
DEVICE, LOSE ANY DATA FROM YOUR PHONE, COMPUTER OR NETWORK, LOSE SUPPORT OR WARRANTY FROM SAMSUNG
OR ANY OTHER PARTY INVOLVED IN PROVIDING THE PHONE AND/OR RELATED SERVICES TO YOU, OR IF USING
ANY PART OF THIS PROJECT BREAKS ANY AGREEMENT YOU HAVE MADE OR ANY LAW YOU ARE SUBJECT TO IN YOUR COUNTRY.

You have been warned.

Tired of switching to Windows, waiting minutes for response from sluggish Eclipse when you press a key,
and hours when you build your app after changing just a single line of code? This project is for you!

It's still a work in progress, and not everything has been ported yet, but I've already managed to
build a not-so-simple app, sign it, and install it on my phone. Now you can do it as well!

Warning! This is not a one-click solution. Because of license issues, I do NOT include any
files from Samsung. You still need to have your own copy of bada IDE downloaded
and installed on some Windows box (you probably have it already on your VirtualBox machine, don't you?),
but you need it only once, to copy some files required by your new Windows-free SDK.

Bug! Before +Broker.exe+ is ported (or proven to work with +wine+), you still need a Windows machine (possibly virtual)
to download app to your phone. I'm working to solve it.

Last but not least, I do not plan to include a simulator in this project. Real men use real hardware, howgh!


Toolchain
---------

You need GNU Make and bada SDK sources from http://opensource.samsung.com/[opensource.samsung.com].
The Makefile has been tested only with +bada_SDK_2.0.0.zip+.
Download the zip file to the directory where Makefile resides.
Run +make+, and make sure your machine is busy, because otherwise you will die of starvation waiting until
the build completes:

--------------
$ make -j16
--------------

...or any other number, somewhat dependent on number of cores your PC has inside.

If you happen to have downloaded a different version of the archive for some reason,
you have to specify its name explicitly, e.g.:

--------------
$ make MAIN_ARCHIVE=bada_SDK_6.6.6.zip -j16
--------------

It's likely that it fails at some point. In such case, you can run it again without +-j+ option,
to see where it fails. Most likely, the +configure+ options given to one of the packages
are not correct and just worked for me accidentially. Examine, investigate, try again and report, please!

If you're lucky enough, the build completes successfully, and you can now copy the toolchain to
a reasonable location within your file system, e.g.:

--------------
# make INSTPREFIX=/opt/samwave install
--------------

The tools will not be available always. To use the toolchain in a currently active terminal, type:

--------------
$ source /opt/samwave/init.sh
--------------

This tiny script sets +$PATH+ and +$CROSS_COMPILE+ environment variables to make building your applications easier.
Now you can try:

--------------
$ ${CROSS_COMPILE}gcc
arm-bada-eabi-gcc: no input files
--------------


Libraries
---------

To be documented.

Signing your application
------------------------

To be documented.

Installing your application on device
-------------------------------------

To be documented.

License and other legal bullshit
--------------------------------

*bali-sdk* is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
 
*bali-sdk* is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with *bali-sdk*.  If not, see http://www.gnu.org/licenses/[http://www.gnu.org/licenses/].

*GNU* is a registered trademark of the Free Software Foundation.

*Linux* is a registered trademark of Linus Torvalds.

*bada* is a registered trademark of Samsung Electronics Co.,Ltd.

*Windows* is a registered trademark of Microsoft Corporation in the United States and other countries.

*Eclipse* is a registered trademark of the Eclipse Foundation.

